version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  target-branch: "develop"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - josef kolář
  assignees:
    - josef kolář
